### ISSUE TITLE
Version of log file is not compatible with Jet version

### ISSUE THREAD

**Issue by ayiz09** [EricZimmerman/Srum#14]
Error processing file! Message: Version of log file is not compatible with Jet version.

This almost always means the database is dirty and must be repaired. This can be verified by running 'esentutl.exe /mh SRUDB.dat' and examining the 'State' property
Microsoft.Isam.Esent.Interop.EsentBadLogVersionException: Version of log file is not compatible with Jet version
   at Microsoft.Isam.Esent.Interop.Api.JetInit2(JET_INSTANCE& instance, InitGrbit grbit) in D:\ManagedEsent\EsentInterop\Api.cs:line 150
   at Microsoft.Isam.Esent.Interop.Instance.Init(InitGrbit grbit) in D:\ManagedEsent\EsentInterop\Instance.cs:line 217
   at SrumData.Srum..ctor(String fileName, String softwareHive)
   at SrumECmd.Program.DoWork(String f, String r, String d, String csv, String dt, Boolean debug, Boolean trace)

-------------------

Run the repair program encounter same error.

**Comment by AndrewRathbun** [comment]
What OS are you using to repair it? What OS did you acquire the DB from? The OS being used must be equal or newer than the OS from which the DB was acquired. 

For example, if you are trying to repair a DB from W11 on a W10 system, you can only repair that DB on W11 or Server 2022, because the Jet engine of those versions matches the DB being repaired. An older version of the Jet engine cannot repair a DB that was made with a newer version of the Jet engine. 

You can use `esentutl.exe /mh "path/to/DB"` to see which version of the Jet engine the DB was made with to clarify.

**Comment by AndrewRathbun** [comment]
https://www-stellarinfo-com.cdn.ampproject.org/v/s/www.stellarinfo.com/amp/article/check-exchange-database-state-using-eseutil-mh-command.php?amp_gsa=1&amp_js_v=a9&usqp=mq331AQIUAKwASCAAgM%3D#amp_tf=From%20%251%24s&aoh=16942611774333&referrer=https%3A%2F%2Fwww.google.com&ampshare=https%3A%2F%2Fwww.stellarinfo.com%2Farticle%2Fcheck-exchange-database-state-using-eseutil-mh-command.php

Go to the Step 2 images. Format version and Engine version. I'm guessing there's a mismatch there for the DB you're trying to repair, most likely the DB Format is a bigger number (aka newer) than the Engine version (of the OS you're on). Newer engine versions can repair older versions, but not vice versa.

**Comment by ayiz09** [comment]
The issue is resolved. I'm using the older OS.

**Comment by AndrewRathbun** [comment]
As another resource on this topic, please check out one of the recent talks at the SANS DFIR Summit earlier this year that covers this at about the 12:15 mark.

https://youtu.be/X4WTcRdIDAM?si=B06ul1qGvODqRgeR
